name: latitude-llm
windows:
  - workspace: cd .
  - apps:
      layout: main-horizontal
      panes:
        - pnpm dev --filter='./apps/*'
        - cd packages/core && pnpm types:build:watch
        - cd packages/constants && pnpm types:build:watch
  - packages:
      layout: main-horizontal
      panes:
        - pnpm build --filter='./packages/**'
        - cd apps/web && pnpm workers:build
  - docker: docker compose up db redis mailpit --menu=false
  - studio: cd packages/core && pnpm db:studio
