name: Linter & Types

on:
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      workflow_call:
        type: boolean
        required: false
        default: false

jobs:
  node-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Use Turbo to build affected packages
        run: pnpm turbo build --cache-dir=.turbo --filter="./packages/**"

      - name: Prettier
        run: pnpm prettier:check

      - name: Node.js Lint
        run: pnpm lint

      - name: TypeScript
        run: pnpm tc --cache-dir=.turbo

  python-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.x

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: '0.5.10'
          enable-cache: true

      - name: Install Python dependencies
        run: |
          cd packages/sdks/python
          uv venv
          uv sync --all-extras --all-groups

      - name: Python Lint
        run: |
          cd packages/sdks/python
          uv run scripts/lint.py
